name: Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Hello from GitHub Actions"
          echo "Runner OS: ${{ runner.os }}"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub sha: ${{ github.sha }}"
